coverage:
  range: 50..70
  status:
    project:
      default:
        target: auto
        threshold: 10%

fixes:
  - "/home/runner/work/bayesian_ensembles/ensembles/::" # Correct paths

ignore:
  - "setup.py"
  - "*/tests/.*"
  - tests/
  - "__init__.py"
  - "*tests*